services:
  dbserver:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=minitwit
    volumes:
      # Keeps your local MongoDB data from disappearing on restart
      - mongo_local_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build:
      context: ./new
      dockerfile: ../docker/web/Dockerfile.dev
    volumes:
      - ./new:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "8080"
    environment:
      - DB_IP=
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  clidownload:
    image: curlimages/curl
    depends_on:
      webserver:
        condition: service_healthy
    entrypoint: sh -c  "curl http://webserver:8080"

volumes:
  mongo_local_data: