services:
  dbserver:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=minitwit
    volumes:
      - mongo_local_data:/data/db
    healthcheck:
      # Use the strict array syntax so Docker doesn't fail on the pipe
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  webserver:
    build:
      context: ./new
      dockerfile: ../docker/web/Dockerfile.dev
    volumes:
      - ./new:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      # Map host port to container port so you can access it in your browser!
      - "8080:8080"
    environment:
      # Give the Go app the database hostname so it doesn't crash!
      - DB_IP=dbserver
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
      # Give Air 30 seconds to compile your Go code before testing it
      start_period: 30s

  clidownload:
    image: curlimages/curl
    depends_on:
      webserver:
        condition: service_healthy
    entrypoint: sh -c "curl http://webserver:8080"

volumes:
  mongo_local_data: