services:
  dbserver:
    image: ${DOCKER_USERNAME}/dbminitwitimage:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=minitwit
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  webserver:
    image: ${DOCKER_USERNAME}/webminitwitimage:latest
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "5001:5000"
    environment:
      - DB_IP=dbserver
    dns:
      - 8.8.8.8
      - 8.8.4.4