version: '1'
services:
  dbserver:
    image: ${DOCKER_USERNAME}/dbminitwitimage:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=minitwit

  webserver:
    image: ${DOCKER_USERNAME}/webminitwitimage:latest
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "5001:5000"
    environment:
      - DB_IP=dbserver

    volumes:
      - ./new:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4