---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push db image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dbminitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dbminitwitimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dbminitwitimage:webbuildcache,mode=max

      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webminitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/webminitwitimage:mysqlbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/webminitwitimage:mysqlbuildcache,mode=max

#      - name: Build and push flagtoolimage
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./Dockerfile-flagtool
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/flagtoolimage:latest
#          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/flagtoolimage:flagtoolbuildcache
#          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/flagtoolimage:flagtoolbuildcache,mode=max

#      - name: Test minitwit
#        run: |
#          docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
#          yes 2>/dev/null | docker compose up -d
#          docker run --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh_key_golang_minitwit
          chmod 600 ~/.ssh/ssh_key_golang_minitwit
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/ssh_key_golang_minitwit -o StrictHostKeyChecking=no
          '/minitwit/deploy.sh'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}